version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    depends_on:
      - prometheus

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    environment:
      - DATA_SOURCE_NAME=exporter:P@ssw0rd@tcp(host.docker.internal:3306)/
    ports:
      - "9104:9104"
    restart: unless-stopped

  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb_exporter
    environment:
      - MONGODB_URI=mongodb://admin:P@ssw0rd@host.docker.internal:27017
    ports:
      - "9216:9216"
    restart: unless-stopped