global:
  scrape_interval: 15s

scrape_configs:
  
  - job_name: 'mariadb'
    static_configs:
      - targets: ['host.docker.internal:9104']  # używamy host.docker.internal, by dostać się do MariaDB na hosta VM

  
  - job_name: 'mongodb'
    static_configs:
      - targets: ['host.docker.internal:9216']